# Generated by Django 3.2.7 on 2021-10-15 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0002_auto_20211015_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Filmy'},
        ),
        migrations.AlterModelOptions(
            name='zanr',
            options={'verbose_name': 'Žánr', 'verbose_name_plural': 'Žánry'},
        ),
    ]
